Install ant and ivy

diff --git a/wercker-box.yml b/wercker-box.yml
--- a/wercker-box.yml
+++ b/wercker-box.yml
@@ -1,5 +1,5 @@
 name: java
-version: 0.0.1.1-dev
+version: 0.0.1.2-dev
 inherits: wercker/ubuntu12.04-webessentials@0.0.5
 type: main
 platform: ubuntu@12.04
@@ -14,7 +14,7 @@ script: |-
   if [ type java ]; then echo "I expected java to be not available. Aborting."; exit 1; fi
 
   # Add webupd8 team repository that contains the 3 major oracle-java versions
-  sudo add-apt-repository ppa:webupd8team/java -y
+  sudo add-apt-repository ppa:webupd8team/java -y -qq
   sudo apt-get update
 
   # Accept the oracle license
@@ -22,7 +22,14 @@ script: |-
   echo debconf shared/accepted-oracle-license-v1-1 seen true |  sudo debconf-set-selections
   
   # Install oracle-java7
-  sudo apt-get install oracle-java7-installer -qq
+  sudo apt-get install oracle-java7-installer -y -qq
   
   # We should have java again
   if [ ! type java ]; then echo "I expected java to be available after oracle-java7-installer installation. Aborting."; exit 1; fi
+
+  # Install ant
+  sudo apt-get install ant ant-contrib ivy -y -qq
+  
+  # We should have ant and ivy available
+  if [ ! type ant ]; then echo "I expected ant to be available. Aborting."; exit 1; fi
+  if [ ! type ivy ]; then echo "I expected ivy to be available. Aborting."; exit 1; fi
